### ISSUE TITLE
Are ICOFamily's png-flavored icons compatible with Windows?

### ISSUE THREAD

**Issue by danwood** [alexzielenski/ICOFamily#2]
I used ICOFamily to build a favicon.ico file (in 32 pixel and 16 pixel variations) and published to a web page, which I then tested with BrowserShots on several versions of Windows.

It doesn't seem like any of the versions of Windows picked up the favicon!

Looking in the code, I see that the data inside of the icon file is actually PNG data.  Maybe that has to do with it.

Am I missing something, or are these files not actually going to be useable (at least as FavIcons) from Windows browsers?

**Comment by danwood** [comment]
I have done some more digging, and it looks like the PNG-wrapping ico format is only Windows Vista and up.  I'm going to investigate what it would take to write out BMP format for the image data....

http://en.wikipedia.org/wiki/ICO_(file_format)

**Comment by matheweis** [comment]
Have a commit out there that has BMP format (writing only) working now (albeit only uncompressed BMP) - but it does work.
